---
# cPanel Deployment Configuration for Repository Separation
# Repository: /home/misedain/repositories/Miseda-Notificari
# Deploy to: /home/misedain/public_html (only build folder contents)

deployment:
  tasks:
    # Execute the custom deployment script
    - /bin/bash /home/misedain/deploy.sh
    - .vscode/