---
# cPanel Deployment Configuration
# Repository: /home/misedain/repositories/Miseda-Notificari
# Auto-build: Pre-commit hook builds React app automatically
# Deploy target: /home/misedain/public_html (copy build files only)

deployment:
  tasks:
    # Execute the custom deployment script
    # Script copiază automat din repositories/Miseda-Notificari/client/build/* în public_html/
    - /bin/bash /home/misedain/deploy.sh
    - .vscode/